// @ts-check
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// Single source of truth for production URL.
// If the site moves to a different domain later, change ONLY this value
// (and the matching SITE_URL constant in src/consts.ts).
const SITE = 'https://www.srkrec.edu.in';

/** @type {Record<string, import('astro').RedirectConfig>} */
const astroRedirects = {
    "/index.php": { status: 302, destination: "/" },
    "/home.php": { status: 302, destination: "/" },
    "/college_profile.php": { status: 302, destination: "/college-profile/" },
    "/about.php": { status: 302, destination: "/college-profile/" },
    "/vision_mission.php": { status: 302, destination: "/vision/" },
    "/vision.php": { status: 302, destination: "/vision/" },
    "/governing_body.php": { status: 302, destination: "/governing/" },
    "/governing.php": { status: 302, destination: "/governing/" },
    "/advisory_council.php": { status: 302, destination: "/advisory-council/" },
    "/college_committees.php": { status: 302, destination: "/central-committee/" },
    "/committees.php": { status: 302, destination: "/central-committee/" },
    "/financial_committee.php": { status: 302, destination: "/financial-committee/" },
    "/organogram.php": { status: 302, destination: "/org-structure/" },
    "/org_structure.php": { status: 302, destination: "/org-structure/" },
    "/board_of_studies.php": { status: 302, destination: "/board-of-studies/" },
    "/academic_council.php": { status: 302, destination: "/academic-council/" },
    "/president_message.php": { status: 302, destination: "/messages/" },
    "/director_message.php": { status: 302, destination: "/messages/" },
    "/principal_message.php": { status: 302, destination: "/messages/" },
    "/messages.php": { status: 302, destination: "/messages/" },
    "/awards_honours.php": { status: 302, destination: "/awards/" },
    "/awards.php": { status: 302, destination: "/awards/" },
    "/prominent_alumni.php": { status: 302, destination: "/prominent-alumni/" },
    "/alumni.php": { status: 302, destination: "/prominent-alumni/" },
    "/development_plan.php": { status: 302, destination: "/development-plan/" },
    "/idp.php": { status: 302, destination: "/development-plan/" },
    "/vitals.php": { status: 302, destination: "/vitals/" },
    "/leadership.php": { status: 302, destination: "/leadership/" },
    "/leadership_team.php": { status: 302, destination: "/leadership/" },
    "/contactus.php": { status: 302, destination: "/quick-links/" },
    "/contact.php": { status: 302, destination: "/quick-links/" },
    "/contact-us.php": { status: 302, destination: "/quick-links/" },
    "/iqac.php": { status: 302, destination: "/iqac/" },
    "/ugc.php": { status: 302, destination: "/accreditations/" },
    "/aicte.php": { status: 302, destination: "/accreditations/" },
    "/jntuk.php": { status: 302, destination: "/accreditations/" },
    "/nba.php": { status: 302, destination: "/accreditations/" },
    "/naac.php": { status: 302, destination: "/accreditations/" },
    "/siro.php": { status: 302, destination: "/accreditations/" },
    "/accreditations.php": { status: 302, destination: "/accreditations/" },
    "/approvals.php": { status: 302, destination: "/accreditations/" },
    "/nirf.php": { status: 302, destination: "/rank/" },
    "/ariia.php": { status: 302, destination: "/rank/" },
    "/rank.php": { status: 302, destination: "/rank/" },
    "/rankings.php": { status: 302, destination: "/rank/" },
    "/admission.php": { status: 302, destination: "/admission-brochure/" },
    "/admissions.php": { status: 302, destination: "/admission-brochure/" },
    "/admission_brochure.php": { status: 302, destination: "/admission-brochure/" },
    "/admission-brochure.php": { status: 302, destination: "/admission-brochure/" },
    "/procedure.php": { status: 302, destination: "/procedure/" },
    "/admission_procedure.php": { status: 302, destination: "/procedure/" },
    "/programmes.php": { status: 302, destination: "/programmes/" },
    "/programs.php": { status: 302, destination: "/programmes/" },
    "/programmes_offered.php": { status: 302, destination: "/programmes/" },
    "/regulations.php": { status: 302, destination: "/regulations/" },
    "/academic_regulations.php": { status: 302, destination: "/regulations/" },
    "/fee.php": { status: 302, destination: "/fee/" },
    "/fee_structure.php": { status: 302, destination: "/fee/" },
    "/tution_fee.php": { status: 302, destination: "/fee/" },
    "/tuition_fee.php": { status: 302, destination: "/fee/" },
    "/online_fee.php": { status: 302, destination: "/online-fee/" },
    "/scholarship.php": { status: 302, destination: "/fee/" },
    "/syllabus.php": { status: 302, destination: "/syllabus/" },
    "/calendar.php": { status: 302, destination: "/calender/" },
    "/calender.php": { status: 302, destination: "/calender/" },
    "/academic_calendar.php": { status: 302, destination: "/calender/" },
    "/timetables.php": { status: 302, destination: "/time-tables/" },
    "/time_tables.php": { status: 302, destination: "/time-tables/" },
    "/time-tables.php": { status: 302, destination: "/time-tables/" },
    "/placements.php": { status: 302, destination: "/placements/" },
    "/placements_details.php": { status: 302, destination: "/placements-summary/" },
    "/placements_summary.php": { status: 302, destination: "/placements-summary/" },
    "/placements_team.php": { status: 302, destination: "/placements-team/" },
    "/placement_cell.php": { status: 302, destination: "/placements/" },
    "/career.php": { status: 302, destination: "/career-guidance/" },
    "/career_guidance.php": { status: 302, destination: "/career-guidance/" },
    "/internships.php": { status: 302, destination: "/internships/" },
    "/training.php": { status: 302, destination: "/training/" },
    "/training_activities.php": { status: 302, destination: "/training/" },
    "/research.php": { status: 302, destination: "/research-overview/" },
    "/research_overview.php": { status: 302, destination: "/research-overview/" },
    "/research_committees.php": { status: 302, destination: "/research-committees/" },
    "/research_advisory.php": { status: 302, destination: "/research-advisory/" },
    "/research_centers.php": { status: 302, destination: "/research-centers/" },
    "/research_excellence.php": { status: 302, destination: "/research-excellence/" },
    "/research_projects.php": { status: 302, destination: "/research-projects/" },
    "/research_publications.php": { status: 302, destination: "/research-publications/" },
    "/research_supervisors.php": { status: 302, destination: "/research-supervisors/" },
    "/research_ethics.php": { status: 302, destination: "/research-ethics/" },
    "/research_development.php": { status: 302, destination: "/development-cell/" },
    "/rd_cell.php": { status: 302, destination: "/development-cell/" },
    "/development_cell.php": { status: 302, destination: "/development-cell/" },
    "/entrepreneurship_cell.php": { status: 302, destination: "/entrepreneurship-cell/" },
    "/edc.php": { status: 302, destination: "/entrepreneurship-cell/" },
    "/ipr_cell.php": { status: 302, destination: "/ipr-cell/" },
    "/iic.php": { status: 302, destination: "/iic/" },
    "/patents.php": { status: 302, destination: "/patents/" },
    "/mous.php": { status: 302, destination: "/mous/" },
    "/mou.php": { status: 302, destination: "/mous/" },
    "/library.php": { status: 302, destination: "/library/" },
    "/library_rules.php": { status: 302, destination: "/library-rules/" },
    "/digital_library.php": { status: 302, destination: "/digital/" },
    "/digital.php": { status: 302, destination: "/digital/" },
    "/computer_center.php": { status: 302, destination: "/computer-center/" },
    "/tech_center.php": { status: 302, destination: "/tech-center/" },
    "/facilities.php": { status: 302, destination: "/facilities/" },
    "/foreign.php": { status: 302, destination: "/foreign/" },
    "/international.php": { status: 302, destination: "/foreign/" },
    "/hostels.php": { status: 302, destination: "/hostels/" },
    "/hostel.php": { status: 302, destination: "/hostels/" },
    "/transportation.php": { status: 302, destination: "/transportation/" },
    "/transport.php": { status: 302, destination: "/transportation/" },
    "/sports.php": { status: 302, destination: "/sports/" },
    "/student_clubs.php": { status: 302, destination: "/student-clubs/" },
    "/clubs.php": { status: 302, destination: "/student-clubs/" },
    "/activities.php": { status: 302, destination: "/activities/" },
    "/student_activities.php": { status: 302, destination: "/activities/" },
    "/well_being.php": { status: 302, destination: "/well-being/" },
    "/wellbeing.php": { status: 302, destination: "/well-being/" },
    "/code_of_conduct.php": { status: 302, destination: "/code-of-conduct/" },
    "/sustainability.php": { status: 302, destination: "/sustainability/" },
    "/campus_life.php": { status: 302, destination: "/activities/" },
    "/gallery.php": { status: 302, destination: "/gallery/" },
    "/departments.php": { status: 302, destination: "/departments/" },
    "/humanities.php": { status: 302, destination: "/humanities/" },
    "/sh.php": { status: 302, destination: "/humanities/" },
    "/bs.php": { status: 302, destination: "/humanities/" },
    "/civil.php": { status: 302, destination: "/departments/civil/" },
    "/civil_vision.php": { status: 302, destination: "/departments/civil/" },
    "/civil_faculty.php": { status: 302, destination: "/departments/civil/faculty/" },
    "/civil_peos_psos.php": { status: 302, destination: "/departments/civil/academic-programs/" },
    "/civil_courseoutcomes.php": { status: 302, destination: "/departments/civil/academic-programs/" },
    "/civil_infrastructure.php": { status: 302, destination: "/departments/civil/facilities/" },
    "/civil_research.php": { status: 302, destination: "/departments/civil/research-consultancy/" },
    "/civil_publications.php": { status: 302, destination: "/departments/civil/research-consultancy/" },
    "/civil_excellence.php": { status: 302, destination: "/departments/civil/achievements/" },
    "/civil_committee.php": { status: 302, destination: "/departments/civil/committees/" },
    "/civil_committees.php": { status: 302, destination: "/departments/civil/committees/" },
    "/civil_awards.php": { status: 302, destination: "/departments/civil/achievements/" },
    "/civil_achievements.php": { status: 302, destination: "/departments/civil/achievements/" },
    "/civil_placements.php": { status: 302, destination: "/departments/civil/placements/" },
    "/civil_activities.php": { status: 302, destination: "/departments/civil/" },
    "/civil_contact.php": { status: 302, destination: "/departments/civil/" },
    "/civil_newsletter.php": { status: 302, destination: "/departments/civil/newsletter/" },
    "/civil_brochure.php": { status: 302, destination: "/departments/civil/brochure/" },
    "/cse.php": { status: 302, destination: "/departments/cse/" },
    "/cse_vision.php": { status: 302, destination: "/departments/cse/" },
    "/cse_faculty.php": { status: 302, destination: "/departments/cse/faculty/" },
    "/cse_peos_psos.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cse_courseoutcomes.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cse_infrastructure.php": { status: 302, destination: "/departments/cse/facilities/" },
    "/cse_research.php": { status: 302, destination: "/departments/cse/research-consultancy/" },
    "/cse_publications.php": { status: 302, destination: "/departments/cse/research-consultancy/" },
    "/cse_excellence.php": { status: 302, destination: "/departments/cse/achievements/" },
    "/cse_committee.php": { status: 302, destination: "/departments/cse/committees/" },
    "/cse_committees.php": { status: 302, destination: "/departments/cse/committees/" },
    "/cse_awards.php": { status: 302, destination: "/departments/cse/achievements/" },
    "/cse_achievements.php": { status: 302, destination: "/departments/cse/achievements/" },
    "/cse_placements.php": { status: 302, destination: "/departments/cse/placements/" },
    "/cse_activities.php": { status: 302, destination: "/departments/cse/" },
    "/cse_contact.php": { status: 302, destination: "/departments/cse/" },
    "/cse_newsletter.php": { status: 302, destination: "/departments/cse/newsletter/" },
    "/cse_brochure.php": { status: 302, destination: "/departments/cse/brochure/" },
    "/ece.php": { status: 302, destination: "/departments/ece/" },
    "/ece_vision.php": { status: 302, destination: "/departments/ece/" },
    "/ece_faculty.php": { status: 302, destination: "/departments/ece/faculty/" },
    "/ece_peos_psos.php": { status: 302, destination: "/departments/ece/academic-programs/" },
    "/ece_courseoutcomes.php": { status: 302, destination: "/departments/ece/academic-programs/" },
    "/ece_infrastructure.php": { status: 302, destination: "/departments/ece/facilities/" },
    "/ece_research.php": { status: 302, destination: "/departments/ece/research-consultancy/" },
    "/ece_publications.php": { status: 302, destination: "/departments/ece/research-consultancy/" },
    "/ece_excellence.php": { status: 302, destination: "/departments/ece/achievements/" },
    "/ece_committee.php": { status: 302, destination: "/departments/ece/committees/" },
    "/ece_committees.php": { status: 302, destination: "/departments/ece/committees/" },
    "/ece_awards.php": { status: 302, destination: "/departments/ece/achievements/" },
    "/ece_achievements.php": { status: 302, destination: "/departments/ece/achievements/" },
    "/ece_placements.php": { status: 302, destination: "/departments/ece/placements/" },
    "/ece_activities.php": { status: 302, destination: "/departments/ece/" },
    "/ece_contact.php": { status: 302, destination: "/departments/ece/" },
    "/ece_newsletter.php": { status: 302, destination: "/departments/ece/newsletter/" },
    "/ece_brochure.php": { status: 302, destination: "/departments/ece/brochure/" },
    "/eee.php": { status: 302, destination: "/departments/eee/" },
    "/eee_vision.php": { status: 302, destination: "/departments/eee/" },
    "/eee_faculty.php": { status: 302, destination: "/departments/eee/faculty/" },
    "/eee_peos_psos.php": { status: 302, destination: "/departments/eee/academic-programs/" },
    "/eee_courseoutcomes.php": { status: 302, destination: "/departments/eee/academic-programs/" },
    "/eee_infrastructure.php": { status: 302, destination: "/departments/eee/facilities/" },
    "/eee_research.php": { status: 302, destination: "/departments/eee/research-consultancy/" },
    "/eee_publications.php": { status: 302, destination: "/departments/eee/research-consultancy/" },
    "/eee_excellence.php": { status: 302, destination: "/departments/eee/achievements/" },
    "/eee_committee.php": { status: 302, destination: "/departments/eee/committees/" },
    "/eee_committees.php": { status: 302, destination: "/departments/eee/committees/" },
    "/eee_awards.php": { status: 302, destination: "/departments/eee/achievements/" },
    "/eee_achievements.php": { status: 302, destination: "/departments/eee/achievements/" },
    "/eee_placements.php": { status: 302, destination: "/departments/eee/placements/" },
    "/eee_activities.php": { status: 302, destination: "/departments/eee/" },
    "/eee_contact.php": { status: 302, destination: "/departments/eee/" },
    "/eee_newsletter.php": { status: 302, destination: "/departments/eee/newsletter/" },
    "/eee_brochure.php": { status: 302, destination: "/departments/eee/brochure/" },
    "/it.php": { status: 302, destination: "/departments/it/" },
    "/it_vision.php": { status: 302, destination: "/departments/it/" },
    "/it_faculty.php": { status: 302, destination: "/departments/it/faculty/" },
    "/it_peos_psos.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/it_courseoutcomes.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/it_infrastructure.php": { status: 302, destination: "/departments/it/facilities/" },
    "/it_research.php": { status: 302, destination: "/departments/it/research-consultancy/" },
    "/it_publications.php": { status: 302, destination: "/departments/it/research-consultancy/" },
    "/it_excellence.php": { status: 302, destination: "/departments/it/achievements/" },
    "/it_committee.php": { status: 302, destination: "/departments/it/committees/" },
    "/it_committees.php": { status: 302, destination: "/departments/it/committees/" },
    "/it_awards.php": { status: 302, destination: "/departments/it/achievements/" },
    "/it_achievements.php": { status: 302, destination: "/departments/it/achievements/" },
    "/it_placements.php": { status: 302, destination: "/departments/it/placements/" },
    "/it_activities.php": { status: 302, destination: "/departments/it/" },
    "/it_contact.php": { status: 302, destination: "/departments/it/" },
    "/it_newsletter.php": { status: 302, destination: "/departments/it/newsletter/" },
    "/it_brochure.php": { status: 302, destination: "/departments/it/brochure/" },
    "/mech.php": { status: 302, destination: "/departments/mechanical/" },
    "/mechanical.php": { status: 302, destination: "/departments/mechanical/" },
    "/mech_vision.php": { status: 302, destination: "/departments/mechanical/" },
    "/mech_faculty.php": { status: 302, destination: "/departments/mechanical/faculty/" },
    "/mechanical_faculty.php": { status: 302, destination: "/departments/mechanical/faculty/" },
    "/mech_peos_psos.php": { status: 302, destination: "/departments/mechanical/academic-programs/" },
    "/mech_courseoutcomes.php": { status: 302, destination: "/departments/mechanical/academic-programs/" },
    "/mech_infrastructure.php": { status: 302, destination: "/departments/mechanical/facilities/" },
    "/mechanical_infrastructure.php": { status: 302, destination: "/departments/mechanical/facilities/" },
    "/mech_research.php": { status: 302, destination: "/departments/mechanical/research-consultancy/" },
    "/mech_publications.php": { status: 302, destination: "/departments/mechanical/research-consultancy/" },
    "/mech_excellence.php": { status: 302, destination: "/departments/mechanical/achievements/" },
    "/mech_committee.php": { status: 302, destination: "/departments/mechanical/committees/" },
    "/mech_committees.php": { status: 302, destination: "/departments/mechanical/committees/" },
    "/mech_awards.php": { status: 302, destination: "/departments/mechanical/achievements/" },
    "/mech_achievements.php": { status: 302, destination: "/departments/mechanical/achievements/" },
    "/mech_placements.php": { status: 302, destination: "/departments/mechanical/placements/" },
    "/mechanical_placements.php": { status: 302, destination: "/departments/mechanical/placements/" },
    "/mech_activities.php": { status: 302, destination: "/departments/mechanical/" },
    "/mech_contact.php": { status: 302, destination: "/departments/mechanical/" },
    "/mech_newsletter.php": { status: 302, destination: "/departments/mechanical/newsletter/" },
    "/mech_brochure.php": { status: 302, destination: "/departments/mechanical/brochure/" },
    "/csit.php": { status: 302, destination: "/departments/csit/" },
    "/csit_vision.php": { status: 302, destination: "/departments/csit/" },
    "/csit_faculty.php": { status: 302, destination: "/departments/csit/faculty/" },
    "/csit_peos_psos.php": { status: 302, destination: "/departments/csit/academic-programs/" },
    "/csit_courseoutcomes.php": { status: 302, destination: "/departments/csit/academic-programs/" },
    "/csit_infrastructure.php": { status: 302, destination: "/departments/csit/facilities/" },
    "/csit_research.php": { status: 302, destination: "/departments/csit/research-consultancy/" },
    "/csit_publications.php": { status: 302, destination: "/departments/csit/research-consultancy/" },
    "/csit_excellence.php": { status: 302, destination: "/departments/csit/achievements/" },
    "/csit_committee.php": { status: 302, destination: "/departments/csit/committees/" },
    "/csit_committees.php": { status: 302, destination: "/departments/csit/committees/" },
    "/csit_awards.php": { status: 302, destination: "/departments/csit/achievements/" },
    "/csit_achievements.php": { status: 302, destination: "/departments/csit/achievements/" },
    "/csit_placements.php": { status: 302, destination: "/departments/csit/placements/" },
    "/csit_activities.php": { status: 302, destination: "/departments/csit/" },
    "/csit_contact.php": { status: 302, destination: "/departments/csit/" },
    "/aiml.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_faculty.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_vision.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_peos_psos.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_infrastructure.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_research.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_committee.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_awards.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_achievements.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aiml_placements.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/aids.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_faculty.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_vision.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_peos_psos.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_infrastructure.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_research.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_committee.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_awards.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_achievements.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/aids_placements.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_faculty.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_vision.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_peos_psos.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_infrastructure.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_research.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_committee.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_awards.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_achievements.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/csbs_placements.php": { status: 302, destination: "/departments/it/academic-programs/" },
    "/cic.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_faculty.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_vision.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_peos_psos.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_infrastructure.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_research.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_committee.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_awards.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_achievements.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/cic_placements.php": { status: 302, destination: "/departments/cse/academic-programs/" },
    "/csd.php": { status: 302, destination: "/departments/csd/" },
    "/csd_faculty.php": { status: 302, destination: "/departments/csd/faculty/" },
    "/csd_vision.php": { status: 302, destination: "/departments/csd/" },
    "/csd_peos_psos.php": { status: 302, destination: "/departments/csd/academic-programs/" },
    "/csd_infrastructure.php": { status: 302, destination: "/departments/csd/facilities/" },
    "/csd_research.php": { status: 302, destination: "/departments/csd/research-consultancy/" },
    "/csd_committee.php": { status: 302, destination: "/departments/csd/committees/" },
    "/csd_awards.php": { status: 302, destination: "/departments/csd/achievements/" },
    "/csd_achievements.php": { status: 302, destination: "/departments/csd/achievements/" },
    "/csd_placements.php": { status: 302, destination: "/departments/csd/placements/" },
    "/sh_faculty.php": { status: 302, destination: "/humanities/" },
    "/humanities_faculty.php": { status: 302, destination: "/humanities/" },
    "/sh_infrastructure.php": { status: 302, destination: "/humanities/" },
    "/Department_Civil.php": { status: 302, destination: "/departments/civil/" },
    "/Department_CSE.php": { status: 302, destination: "/departments/cse/" },
    "/Department_ECE.php": { status: 302, destination: "/departments/ece/" },
    "/Department_EEE.php": { status: 302, destination: "/departments/eee/" },
    "/Department_IT.php": { status: 302, destination: "/departments/it/" },
    "/Department_Mechanical.php": { status: 302, destination: "/departments/mechanical/" },
    "/Civil_Department.php": { status: 302, destination: "/departments/civil/" },
    "/CSE_Department.php": { status: 302, destination: "/departments/cse/" },
    "/ECE_Department.php": { status: 302, destination: "/departments/ece/" },
    "/EEE_Department.php": { status: 302, destination: "/departments/eee/" },
    "/IT_Department.php": { status: 302, destination: "/departments/it/" },
    "/Mechanical_Department.php": { status: 302, destination: "/departments/mechanical/" },
    "/Departments.php": { status: 302, destination: "/departments/" },
    "/Faculty.php": { status: 302, destination: "/departments/" },
    "/Placements.php": { status: 302, destination: "/placements/" },
    "/Iqac.php": { status: 302, destination: "/iqac/" },
    "/About.php": { status: 302, destination: "/college-profile/" },
  };

export default defineConfig({
  site: SITE,
  trailingSlash: 'ignore',
  redirects: astroRedirects,
  integrations: [
    mdx(),
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
      // Exclude template demo / backup / test pages from the sitemap so Google
      // never sees them. Matching paths still build (until we delete them),
      // but they won't be advertised to search engines.
      filter: (page) => {
        const blocked = [
          '/index-bk',
          '/index-copy',
          '/index-two',
          '/index-three',
          '/index-four',
          '/index-five',
          '/test',
          '/blog/first-post',
          '/blog/second-post',
        ];
        return !blocked.some((b) => page.includes(b));
      },
      serialize: (item) => {
        // Higher priority for top-level/important pages
        if (item.url === `${SITE}/` || item.url === `${SITE}`) {
          return { ...item, priority: 1.0, changefreq: /** @type {any} */ ('daily') };
        }
        if (/\/departments\/[^/]+\/?$/.test(item.url)) {
          return { ...item, priority: 0.9 };
        }
        if (/\/(programmes|admission-brochure|placements|college-profile|departments)\/?$/.test(item.url)) {
          return { ...item, priority: 0.9 };
        }
        return item;
      },
    }),
  ],
  devToolbar: {
    enabled: false,
  },
  build: {
    inlineStylesheets: 'auto',
  },
  compressHTML: true,
});
